// Litle PayPage Stuff


var litleFunctions = {
    setLitleResponseFields: function (response) {
        document.getElementById('response__code').value         = response.response;
        document.getElementById('response__message').value      = response.message;
        document.getElementById('response__responseTime').value = response.responseTime;
        document.getElementById('response__litleTxnId').value   = response.litleTxnId;
        document.getElementById('response__type').value         = response.type;
    },

    // This is a random GUID. Same format as the basket ID we use on the real checkout - which is generated by the API
    generateOrderID: function () {
        var r4 = function() {
           return (((1+Math.random())*0x10000)|0).toString(16).substring(1).toUpperCase();
        };

        return (r4()+r4()+"-"+r4()+"-"+r4()+"-"+r4()+"-"+r4()+r4()+r4());
    },

    timeoutOnLitle: function () {
        var $responseOutput = $("<pre/>").text("API Unavailable - Timeout");
    
        $(".api-response").prepend($responseOutput).show();
    
        return false;
    },

    logResponse: function (response) {
        litleFunctions.setLitleResponseFields(response);

        // Pretty print the JSON and display it.
        var $responseOutput = $("<pre/>").text(JSON.stringify(response, undefined, 2));
        $(".api-response").prepend($responseOutput).show();

        return false;
    },

    submitAfterLitle: function (response) {
        litleFunctions.setLitleResponseFields(response);

        return false;
    }
}


// The acutal binding to the submit function
$("#submit-payment").click(function() {

    if (typeof new LitlePayPage() !== "object") {
        litleFunctions.logResponse("API Unavailable");

        return false;
    }

    // Normally this data is provided by our API, generate random GUIDs for this minimal testcase
    $("#request__orderId").val( litleFunctions.generateOrderID() );
    $("#request__merchantTxnId").val( litleFunctions.generateOrderID() );


    // Clear anything that may be in the form fields
    litleFunctions.setLitleResponseFields({
        "response": "",
        "message": ""
    });

    // Setup the request
    var litleRequest = {
        "paypageId":    document.getElementById("request__paypageId").value,
        "reportGroup":  document.getElementById("request__reportGroup").value,
        "orderId":      document.getElementById("request__orderId").value,
        "id":           document.getElementById("request__merchantTxnId").value,
        "url":          "https://request-prelive.np-securepaypage-litle.com"
    };

    // Get the data from the form fields. Note we are using browser native selectors
    // Litle API requires the element directly, not the value, and not a jQuery object
    var formFields = {
        "accountNum":             document.getElementById("card-number"),
        "cvv2":                   document.getElementById("cvv2"),
        "paypageRegistrationId":  document.getElementById("response__paypageRegistrationId"),
        "bin":                    document.getElementById("response__bin")
    };

    new LitlePayPage().sendToLitle(
        litleRequest, formFields, litleFunctions.submitAfterLitle, litleFunctions.logResponse, litleFunctions.timeoutOnLitle, 5000
    );

    return false;
});

